apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: flask
  labels:
    app: sushil-flask-app
    tier: frontend
spec:

  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: kubernetes-sba-cluster
        image: sushilgautam/sushil-flask-app
        ports:
          - containerPort: 88
